name: ai300-training
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pip:
      - mlflow==2.22.1
      - azureml-mlflow==1.62.0.post6